version: '3.5'
services:
  db:
    build:
      context: ./
      dockerfile: docker/dockerfiles/mysql/Dockerfile
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: eng
    volumes:
      - ./docker/volumes/mysql_vol:/var/lib/mysql